{% set name = "gpq" %}
{% set version = "0.24.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/planetlabs/gpq/archive/v{{ version }}.tar.gz 
  sha256: a7cf06f5f48a4db593c147e800d684ce74a9d4a269593f3fec30442f8906efb1

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-cgo') }}
    - go >=1.19
  host:
  run:

test:
  commands:
    - gpq --help

about:
  home: https://github.com/planetlabs/gpq
  summary: Utility for working with GeoParquet
  license: Apache-2.0
  license_file:
    - LICENSE
   

extra:
  recipe-maintainers:
    - andersy005